[package]
name = "spl-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "1.14.6"
solana-sdk = "1.14.6"
spl-associated-token-account = "1.1.2"
spl-token = "3.5.0"
